disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Muntasir Islam"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "14 January"
  logo = "logo.png"
  secondaryLogo = "img/secondary-logo.png"
  description = "My awesome website"
  copyright = "Muntasir Islam &copy;2024  All Right reserved "

[params.author]
  name = "Muntasir Islam"
  email = "muntasirislamseo@gmail.com"
  image = "profile-pic.png"
  imageQuality = 96
   headline = "Freelance SEO Consultant In Bangladesh (Dinajpur)"
   bio = "My name is Muntasir Islam. I'm a freelance SEO consultant delivering exceptional results for brands and marketing agencies. I am based in Dinajpur but work with businesses across the World. I pursue a people-first approach to SEO, which I believe is in the best interest of your customers, search engines and ultimately your business goals. Although there are many intricacies to SEO, the best results come with a simple, no-BS approach."
  links = [
     { email = "mailto:muntasirislamseo@gmail.com" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { bluesky = "https://bsky.app/profile/username" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
    { facebook = "https://facebook.com/muntasirislam.eee" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
      { github = "https://github.com/muntarockz" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
      { linkedin = "https://linkedin.com/in/muntarockz" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
      { whatsapp = "https://wa.me/+8801751169651" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
  ]
